### ISSUE TITLE
Installing plugin broke PyCharm

### ISSUE THREAD

**Issue by MikhailPasechnik** [Quick-Turn-Studio/CLionSupportForQt#7]
1. Folders containing .qml files not accesable
![image](https://user-images.githubusercontent.com/11280047/84506851-9e731400-acc8-11ea-83fb-5cce1a42980c.png)
2. File -> Settings dialog not opening
3. Only way to repair PyCharm is to click `Disable plugin...` in stack trace dialog.

Stack Trace:

```
com.intellij.ide.plugins.MainRunner$StartupAbortedException: Fatal error initializing 'com.intellij.psi.impl.cache.impl.todo.TodoIndex'
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:125)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2400)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.executeNestedInitializationTask(IndexInfrastructure.java:217)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.runParallelNestedInitializationTasks(IndexInfrastructure.java:205)
	at com.intellij.util.indexing.IndexInfrastructure$DataInitialization.call(IndexInfrastructure.java:166)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.lambda$run$0(BoundedTaskExecutor.java:185)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:181)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ExceptionInInitializerError
	at quickturnstudio.sdk.language.qml.QmlFileType.<init>(QmlFileType.java)
	at quickturnstudio.sdk.language.qml.QmlFileType.<clinit>(QmlFileType.java)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:41)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:34)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiateFileTypeBean(FileTypeManagerImpl.java:428)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.instantiatePendingFileTypes(FileTypeManagerImpl.java:419)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.getRegisteredFileTypes(FileTypeManagerImpl.java:1176)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex.getVersion(TodoIndex.java:109)
	at com.intellij.util.indexing.FileBasedIndexImpl.registerIndexer(FileBasedIndexImpl.java:337)
	at com.intellij.util.indexing.FileBasedIndexImpl.access$5500(FileBasedIndexImpl.java:99)
	at com.intellij.util.indexing.FileBasedIndexImpl$FileIndexDataInitialization.lambda$initAssociatedDataForExtensions$0(FileBasedIndexImpl.java:2394)
	... 12 more
Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'QML' is already registered: class name.kropp.intellij.qml.QmlLanguage
	at com.intellij.lang.Language.<init>(Language.java:82)
	at com.intellij.lang.Language.<init>(Language.java:58)
	at com.intellij.lang.Language.<init>(Language.java:54)
	at quickturnstudio.sdk.language.qml.IIIIIIIIIIIiIIIiIIIIIiIiiIiiiIiIIiIIiiiiiiIiiIIiIIIIiI.<init>(QmlLanguage.java)
	at quickturnstudio.sdk.language.qml.IIIIIIIIIIIiIIIiIIIIIiIiiIiiiIiIIiIIiiiiiiIiiIIiIIIIiI.<clinit>(QmlLanguage.java)
	... 25 more
```

**Comment by MikhailPasechnik** [comment]
I suspect that it is caused by another plugin thats declares class name.kropp.intellij.qml.QmlLanguage 
https://plugins.jetbrains.com/plugin/9532-qml-support

**Comment by grabusr** [comment]
Hello Mikhail,

This can happen when you have installed and activated both plugins: QML Editor and QML support.
Did you disable QML support plugin?

**Comment by MikhailPasechnik** [comment]
> Hello Mikhail,
> 
> This can happen when you have installed and activated both plugins: QML Editor and QML support.
> Did you disable QML support plugin?

Hello grabusr!
Yes, disabling qml-support plugin solved this!

**Comment by grabusr** [comment]
Great! Thank you for reporting the issue!
Let us know if you discover another problem or request a feature.
